UniversityManagementSystemPortalWeb/Controllers/EmployeController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Serialization;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Text;
using UniversityManagementSystemPortalWeb.ViewModels;
using UniversityManagementSystemPortal.ModelDto.Employee;
using UniversityManagementSystemPortal.Models.ModelDto.Department;
using UniversityManagementSystemPortal.Models.ModelDto.Position;
using Microsoft.AspNetCore.Mvc.Rendering;
using UniversityManagementSystemPortalWeb.Authorization;

namespace UniversityManagementSystemPortalWeb.Controllers
{
    [CustomAuth("Admin")]
    public class EmployeController : Controller
    {
        private readonly IHttpClientFactory _clientFactory;

        public EmployeController(IHttpClientFactory clientFactory)
        {
            _clientFactory = clientFactory;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult EmployeeRegister()
        {
            var departments = GetDepartments();
            var positions = GetPositions();

            ViewBag.Departments = new SelectList(departments.Result, "Id", "Name");
            ViewBag.Positions = new SelectList(positions.Result, "Id", "Name");

            var model = new EmployeeUserViewModel();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
 
        public async Task<IActionResult> EmployeeRegister([FromForm] EmployeeUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                // Saving the user details and getting the User ID
                var (success, userId, errors) = await SaveUserAsync(model.userDto);

                if (success)
                {
                    // Assigning the User ID to the Employee
                    model.createEmployeeDto.UserId = userId;

                    // Saving the employee
                    var (empSuccess, empErrors) = await SaveEmployeeAsync(model.createEmployeeDto);

                    if (empSuccess)
                    {
                        // Return success message to the user
                        return Json(new { success = true, message = "Employee registration successful." });
                    }
                    else
                    {
                        // Return the error messages to the user
                        return Json(new { success = false, message = "Error in saving Employee", errors = empErrors });
                    }
                }
                else
                {
                    // Return the error messages to the user
                    return Json(new { success = false, message = "Error in saving User", errors = errors });
                }
            }

            ViewBag.Departments = new SelectList(await GetDepartments(), "Id", "Name");
            ViewBag.Positions = new SelectList(await GetPositions(), "Id", "Name");

            return View(model);
        }
        private async Task<List<LookupDto>> GetDepartments()
        {
            var request = new HttpRequestMessage(HttpMethod.Get,
                "https://localhost:7092/api/Department/lookup");

            var client = _clientFactory.CreateClient();

            var response = await client.SendAsync(request);

            if (response.IsSuccessStatusCode)
            {
                return await response.Content.ReadFromJsonAsync<List<LookupDto>>();
            }

            return new List<LookupDto>();
        }

        private async Task<List<LookupPositiondto>> GetPositions()
        {
            var request = new HttpRequestMessage(HttpMethod.Get,
                "https://localhost:7092/api/Position/Lookup");

            var client = _clientFactory.CreateClient();

            var response = await client.SendAsync(request);

            if (response.IsSuccessStatusCode)
            {
                return await response.Content.ReadFromJsonAsync<List<LookupPositiondto>>();
            }

            return new List<LookupPositiondto>();
        }
        private async Task<(bool success, Guid userId, List<string> errors)> SaveUserAsync(RegistorUserDto userDto)
        {
            try
            {
                using (var handler = new HttpClientHandler())
                {
                    handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => true;

                    using (var client = new HttpClient(handler))
                    {
                        // Account API call
                        client.BaseAddress = new Uri("https://localhost:7092/api/Account/");
                        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));
                        client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                        var jsonPayload = JsonConvert.SerializeObject(userDto, new JsonSerializerSettings { ContractResolver = new CamelCasePropertyNamesContractResolver() });
                        jsonPayload = jsonPayload.Insert(1, $"\"id\":\"{userDto.Id}\",");
                        Console.WriteLine("JSON Payload: " + jsonPayload); // Log the JSON payload
                        var content = new StringContent(jsonPayload, Encoding.UTF8, "application/json");
                        HttpResponseMessage responseMessage = await client.PostAsync("post", content);

                        if (responseMessage.IsSuccessStatusCode) // Check if Account API returns 200 status code
                        {
                            var resultContent = await responseMessage.Content.ReadAsStringAsync();
                            Console.WriteLine("API Result Content: " + resultContent); // Log the result content
                            var result = JsonConvert.DeserializeObject<RegistorUserDto>(resultContent);

                            if (result != null && result.Id != Guid.Empty)
                            {
                                return (true, result.Id, new List<string>());
                            }
                            else
                            {
                                // Handle error when retrieving User ID
                                return (false, Guid.Empty, new List<string> { "An error occurred while retrieving the User ID. Result content: " + resultContent });
                            }
                        }
                        else
                        {
                            // Handle error when creating the User
                            var errorContent = await responseMessage.Content.ReadAsStringAsync();
                            var errors = JsonConvert.DeserializeObject<List<string>>(errorContent);
                            return (false, Guid.Empty, errors);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                return (false, Guid.Empty, new List<string> { ex.Message });
            }
        }
       
        private async Task<(bool success, List<string> errors)> SaveEmployeeAsync(CreateEmployeeDto createEmployeeDto)
        {
            try
            {
                using (var handler = new HttpClientHandler())
                {
                    handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => true;

                    using (var client = new HttpClient(handler))
                    {
                        // Employee API call
                        client.BaseAddress = new Uri("https://localhost:7092/api/employees");
                        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));
                        client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                        var content = new MultipartFormDataContent();
                        foreach (var prop in createEmployeeDto.GetType().GetProperties())
                        {
                            if (prop.GetValue(createEmployeeDto) != null)
                            {
                                content.Add(new StringContent(prop.GetValue(createEmployeeDto).ToString()), $"\"{prop.Name}\"");
                            }
                        }

                        HttpResponseMessage responseMessage = await client.PostAsync("", content);

                        if (responseMessage.IsSuccessStatusCode)
                        {
                            return (true, new List<string>());
                        }
                        else
                        {
                            // Handle error when saving the Employee information
                            var errorContent = await responseMessage.Content.ReadAsStringAsync();
                            var errors = JsonConvert.DeserializeObject<List<string>>(errorContent);
                            return (false, errors);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                return (false, new List<string> { ex.Message });
            }
        }

    }
}

UniversityManagementSystemPortalWeb/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using System.Net.Http.Headers;
using System.Text;
using UniversityManagementSystemPortal;
using UniversityManagementSystemPortalWeb.ViewModels;

namespace UniversityManagementSystemPortalWeb.Controllers
{
    public class StudentController : Controller
    {
        private readonly IHttpClientFactory _clientFactory;
        public StudentController(IHttpClientFactory clientFactory)
        {
            _clientFactory = clientFactory;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult StudentRegister()
        {
            //get department
            //get positions
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> StudentRegister([FromForm] StudentUserViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Save the User information first
                    var userResult = await SaveUserAsync(model.userDto);

                    if (userResult.success)
                    {
                        // Save the Student information with the returned UserId
                        model.studentDto.UserId = userResult.userId;
                        var studentResult = await SaveStudentAsync(model.studentDto);

                        if (studentResult.success)
                        {
                            return Json(new { success = true, message = "Student registered successfully." });
                        }
                        else
                        {
                            return Json(new { success = false, error = "An error occurred while saving the Student details.", errors = studentResult.errors });
                        }
                    }
                    else
                    {
                        return Json(new { success = false, error = "An error occurred while creating the User.", errors = userResult.errors });
                    }
                }
                else
                {
                    return Json(new { success = false, error = "Invalid model state." });
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, error = ex.Message });
            }
        }

        private async Task<(bool success, Guid userId, List<string> errors)> SaveUserAsync(RegistorUserDto userDto)
        {
            try
            {
                using (var handler = new HttpClientHandler())
                {
                    handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => true;

                    using (var client = new HttpClient(handler))
                    {
                        // Account API call
                        client.BaseAddress = new Uri("https://localhost:7092/api/Account/");
                        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));
                        client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                        var jsonPayload = JsonConvert.SerializeObject(userDto, new JsonSerializerSettings { ContractResolver = new CamelCasePropertyNamesContractResolver() });
                        jsonPayload = jsonPayload.Insert(1, $"\"id\":\"{userDto.Id}\",");
                        Console.WriteLine("JSON Payload: " + jsonPayload); // Log the JSON payload
                        var content = new StringContent(jsonPayload, Encoding.UTF8, "application/json");
                        HttpResponseMessage responseMessage = await client.PostAsync("post", content);

                        if (responseMessage.IsSuccessStatusCode) // Check if Account API returns 200 status code
                        {
                            var resultContent = await responseMessage.Content.ReadAsStringAsync();
                            Console.WriteLine("API Result Content: " + resultContent); // Log the result content
                            var result = JsonConvert.DeserializeObject<RegistorUserDto>(resultContent);

                            if (result != null && result.Id != Guid.Empty)
                            {
                                return (true, result.Id, new List<string>());
                            }
                            else
                            {
                                // Handle error when retrieving User ID
                                return (false, Guid.Empty, new List<string> { "An error occurred while retrieving the User ID. Result content: " + resultContent });
                            }
                        }
                        else
                        {
                            // Handle error when creating the User
                            var errorContent = await responseMessage.Content.ReadAsStringAsync();
                            var errors = JsonConvert.DeserializeObject<List<string>>(errorContent);
                            return (false, Guid.Empty, errors);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                return (false, Guid.Empty, new List<string> { ex.Message });
            }
        }

        private async Task<(bool success, List<string> errors)> SaveStudentAsync(AddStudentDto studentDto)
        {
            try
            {
                using (var handler = new HttpClientHandler())
                {
                    handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => true;

                    using (var client = new HttpClient(handler))
                    {
                        // Student API call immediately after successful Account API call
                        client.BaseAddress = new Uri("https://localhost:7092/api/Student/");
                        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));
                        client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                        var content = new MultipartFormDataContent();
                        foreach (var prop in studentDto.GetType().GetProperties())
                        {
                            if (prop.GetValue(studentDto) != null)
                            {
                                content.Add(new StringContent(prop.GetValue(studentDto).ToString()), $"\"{prop.Name}\"");
                            }
                        }

                        HttpResponseMessage responseMessage = await client.PostAsync("https://localhost:7092/api/Student", content);

                        if (responseMessage.IsSuccessStatusCode)
                        {
                            return (true, new List<string>());
                        }
                        else
                        {
                            // Handle error when saving the Student information
                            var errorContent = await responseMessage.Content.ReadAsStringAsync();
                            var errors = JsonConvert.DeserializeObject<List<string>>(errorContent);
                            return (false, errors);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                return (false, new List<string> { ex.Message });
            }
        }


        [HttpGet]
        public IActionResult GetCsrfToken()
        {
            return Content(HttpContext.Request.Cookies["__RequestVerificationToken"], "text/plain");
        }
    }
}

UniversityManagementSystemPortalWeb/Views/Employe/EmployeeRegister.cshtml
@using UniversityManagementSystemPortal.Enum;
@using UniversityManagementSystemPortal;
@using UniversityManagementSystemPortalWeb.ViewModels;
@model EmployeeUserViewModel

@{
    ViewBag.Title = "Student Registration";
}
<head>
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        h1 {
            text-align: center;
            color: #333;
        }

        h3 {
            color: #444;
        }

        form {
            width: 80%;
            margin: 0 auto;
            background-color: #f7f7f7;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);
        }

        label {
            display: block;
            margin-bottom: 5px;
            color: #555;
        }

        input, textarea, select {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        button {
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        #submitBtn {
            background-color: #007bff;
            color: #fff;
        }
    </style>
</head>
<body>
    <h1>General Detail</h1>
    @if (ViewBag.ErrorMessage != null)
    {
        <div class="alert alert-danger">@ViewBag.ErrorMessage</div>
    }
    <form id="registrationForm" asp-controller="Student" asp-action="StudentRegister" method="post" enctype="multipart/form-data">
        @Html.AntiForgeryToken()
        <h3>Personal Details</h3>
        <div>
            <label asp-for="createEmployeeDto.EmployeeNo">EmployeeNo</label>
            <input asp-for="createEmployeeDto.EmployeeNo" name="createEmployeeDto.EmployeeNo" />
        </div>
        <div>
            <label asp-for="createEmployeeDto.EmployeeType">EmployeeType</label>
            <select asp-for="createEmployeeDto.EmployeeType" asp-items="Html.GetEnumSelectList<EmployeeType>()"></select>
        </div>
        <div>
            <label asp-for="createEmployeeDto.JoiningDate">JoiningDate</label>
            <input input type="date" asp-for="createEmployeeDto.JoiningDate" name="createEmployeeDto.JoiningDate" />
        </div>

        <div>
            <label asp-for="userDto.FirstName">First Name</label>
            <input asp-for="userDto.FirstName" name="userDto.FirstName" />
        </div>
        <div>
            <label asp-for="userDto.MiddleName">Middle Name</label>
            <input asp-for="userDto.MiddleName" name="userDto.MiddleName" />
        </div>
        <div>
            <label asp-for="userDto.LastName">Last Name</label>
            <input asp-for="userDto.LastName" name="userDto.LastName" />
        </div>
        <div>
            <label asp-for="userDto.Email">Email</label>
            <input type="email" asp-for="userDto.Email" name="userDto.Email" />
        </div>
        <div>
            <label asp-for="userDto.Gender">Gender</label>
            <select asp-for="userDto.Gender" asp-items="Html.GetEnumSelectList<Gender>()" name="userDto.Gender"></select>
        </div>
        <div>
            <label asp-for="userDto.DateOfBirth">Date of Birth</label>
            <input type="date" asp-for="userDto.DateOfBirth" name="userDto.DateOfBirth" />
        </div>
        <div>
            <label asp-for="createEmployeeDto.DepartmentId">Department</label>
            <select asp-for="createEmployeeDto.DepartmentId" asp-items="ViewBag.Departments"></select>
        </div>

        <div>
            <label asp-for="createEmployeeDto.PositionId">Position</label>
            <select asp-for="createEmployeeDto.PositionId" asp-items="ViewBag.Positions"></select>
        </div>
        <div>
            <label asp-for="userDto.MobileNo">Mobile No</label>
            <input asp-for="userDto.MobileNo" name="userDto.MobileNo" />
        </div>
        <div>
            <label asp-for="userDto.BloodGroup">Blood Group</label>
            <select asp-for="userDto.BloodGroup" asp-items="Html.GetEnumSelectList<BloodGroup>()" name="userDto.BloodGroup"></select>
        </div>
        <div>
            <label asp-for="userDto.Username">Username</label>
            <input asp-for="userDto.Username" name="userDto.Username" />
        </div>
        <div>
            <label asp-for="userDto.Password">Password</label>
            <input type="password" asp-for="userDto.Password" name="userDto.Password" />
        </div>
        <input type="hidden" asp-for="createEmployeeDto.UserId" name="createEmployeeDto.UserId" />
        <div>
            <label asp-for="createEmployeeDto.Address">Address</label>
            <textarea asp-for="createEmployeeDto.Address"></textarea>
        </div>
        <div>
            <label asp-for="createEmployeeDto.Picture">Picture</label>
            <input type="file" asp-for="createEmployeeDto.Picture" />
        </div>

        <button type="submit" id="submitBtn">Save Student Details</button>
    </form>
    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
        <script>
            $(document).ready(function () {
                $("#registrationForm").on("submit", function (event) {
                    event.preventDefault();

                    const formElement = document.getElementById("registrationForm");
                    let ajaxData = new FormData(formElement);

                    $.ajax({
                        url: "@Url.Action("EmployeeRegister", "Employe")",
                        type: "POST",
                        data: ajaxData,
                        processData: false,
                        contentType: false,
                        headers: {
                            RequestVerificationToken: getCsrfToken()
                        },
                        success: function (data) {
                            if (data.success) {
                                alert("Successfully submitted the form.");
                            } else {
                                let errorMessage = "Error submitting the form: " + data.error;
                                if (data.errors) {
                                    errorMessage += "\n\nErrors:\n" + data.errors.join("\n");
                                }
                                alert(errorMessage);
                            }
                        },
                        error: function (xhr, status, error) {
                            if (xhr.status === 400) {
                                alert("Error: Bad Request. Please check your input data and try again.");
                            } else {
                                alert("Error: " + xhr.responseText);
                            }
                        }
                    });
                });

                function getCsrfToken() {
                    const tokenInput = document.querySelector('input[name="__RequestVerificationToken"]');
                    return tokenInput ? tokenInput.value : '';
                }
            });
        </script>
    }

</body>